services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: ./php.dockerfile
    image: php
    user: "1000:1000"
    container_name: coursecasts_forum_php
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ../:/var/www/html/
    networks:
      - coursecasts-forum-network

  #Nginx Service
  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile: ./nginx.dockerfile
    container_name: coursecasts_forum_nginx
    restart: unless-stopped
    volumes:
      - ../:/var/www/html
    tty: true
    ports:
      - "8003:80"
    networks:
      - coursecasts-forum-network
  
  #Mysql DB
  mysql:
    image: mysql:8.0
    container_name: coursecasts_forum_mysql
    restart: unless-stopped
    tty: true
    ports:
        - "33062:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql:/mysql
    networks:
      - coursecasts-forum-network

  # phpMyAdmin Service
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: coursecasts_forum_pma
    depends_on:
      - mysql
    ports:
      - 8083:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    networks:
      - coursecasts-forum-network

  #MailHog
  mailhog:
    image: mailhog/mailhog
    container_name: coursecasts_forum_mailhog
    ports:
        - "1025:1025"
        - "1085:8025"
    networks:
        - coursecasts-forum-network

  node:
    build:
      context: .
      dockerfile: ./node.dockerfile
    container_name: coursecasts_forum_node
    stdin_open: true
    restart: always
    working_dir: /app
    volumes:
      - ../:/app
      - /app/node_modules
    networks:
      - coursecasts-forum-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    expose: 
      - "5173"
    ports: 
      - "5173:5173"

  # MeiliSearch Service
  meilisearch:
    image: getmeili/meilisearch
    container_name: coursecasts_forum_meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meili_data:/meili_data
    networks:
      - coursecasts-forum-network

#Docker Networks
networks:
  coursecasts-forum-network:
    name: coursecasts-forum-network

volumes:
  mysql:
    driver: local
  meili_data:
    driver: local